kmj_pay_pal_bridge:
    environment: sandbox
    sandbox:
        clientId: 'Aa8mlBAEsT9MczjYi6ebt7itE9VYql6Io8pBtagVfs7R_Ztzw6BDdM6ojOfQ'
        secret: 'EMtXnhBpFI4wDyyYf-ogDsx2A5S1MxqEpbgtIrI3FvqNcejB_zSVsrd8BuY5' 
    production:
        clientId: 'Aa8mlBAEsT9MczjYi6ebt7itE9VYql6Io8pBtagVfs7R_Ztzw6BDdM6ojOfQ'
        secret: 'EMtXnhBpFI4wDyyYf-ogDsx2A5S1MxqEpbgtIrI3FvqNcejB_zSVsrd8BuY5' 
    logs:
        enabled: true                                   
        filename: %kernel.root_dir%/logs/paypal.log    
        level: FINE                                  
    http:
        timeout: 30                                 
        retry: true