kmj_pay_pal_bridge:
    environment: sandbox
    sandbox:
        clientId: 'AedZ1hBqvGPZ3oNqu5WsFJgbN3fbc6tPj8nj6ZfFiO9GpNp3xHxZhw-IZepb'
        secret: 'EOA-lRDO4rA1mso6-kdVOKu6GjEHGdUDHXAJI6SYJl2kUlabT6BayKh-PtJH' 
    production:
        clientId: 'AedZ1hBqvGPZ3oNqu5WsFJgbN3fbc6tPj8nj6ZfFiO9GpNp3xHxZhw-IZepb'
        secret: 'EOA-lRDO4rA1mso6-kdVOKu6GjEHGdUDHXAJI6SYJl2kUlabT6BayKh-PtJH' 
    logs:
        enabled: true                                   
        filename: %kernel.root_dir%/logs/paypal.log    
        level: FINE                                  
    http:
        timeout: 30                                 
        retry: true