// Generated by CoffeeScript 1.8.0
var Init;

Init = (function() {
  function Init() {}

  return Init;

})();

$(function() {
  setTimeout(function() {
    $('#inscription').addClass("scale");
  }, 10000);
  return 1;
});
