// Generated by CoffeeScript 1.8.0
var Cart, ChangePassword, Click, Init;

Init = (function() {
  function Init() {
    this.button = new Click($('#cart')).buttonCart();
    new Click($('#button')).buttonAfficheChangePassword();
  }

  return Init;

})();

Click = (function() {
  function Click(selector) {
    this.selector = selector;
  }

  Click.prototype.buttonCart = function() {
    return $(this.selector).on("click", function() {
      var cart;
      cart = new Cart($('#cart'));
      cart.ajax();
      return false;
    });
  };

  Click.prototype.buttonAfficheChangePassword = function() {
    return this.selector.on("click", 'a', function() {
      new ChangePassword($(this)).ajax();
      return false;
    });
  };

  Click.prototype.buttonChangePassword = function() {
    return this.selector.on("submit", function() {
      new ChangePassword($(this)).ajaxForm();
      return false;
    });
  };

  return Click;

})();

ChangePassword = (function() {
  function ChangePassword(button) {
    this.button = button;
  }

  ChangePassword.prototype.ajaxForm = function() {
    console.log(this.button.attr('action'));
    return $.ajax({
      url: 'compte/change-mot-de-passe',
      success: function(html) {
        return console.log(html);
      }
    });
  };

  ChangePassword.prototype.ajax = function() {
    return $.ajax({
      url: this.button.attr('href'),
      success: function(html) {
        var options;
        options = $('#options');
        return options.fadeOut({
          complete: function() {
            options.empty().append($(html));
            return new Click($('#changePassword')).buttonChangePassword();
          }
        }).fadeIn();
      }
    });
  };

  return ChangePassword;

})();

Cart = (function() {
  function Cart(button) {
    this.button = button;
  }

  Cart.prototype.ajax = function() {
    return $.ajax({
      url: this.button.attr('href'),
      success: function(html) {
        var addRemove, cart, newButton, panier;
        addRemove = $('#addRemove');
        panier = '#panier';
        html = $(html);
        cart = html.find(panier).text();
        $(panier).text(cart);
        newButton = html.find('#cart');
        new Click(newButton).buttonCart();
        return addRemove.hide({
          effect: 'slide',
          direction: 'left',
          easing: 'easeInExpo',
          duration: 800,
          complete: function() {
            $('#cart').remove();
            return addRemove.prepend(newButton);
          }
        }).show({
          effect: "slide",
          direction: 'right',
          easing: 'easeInExpo',
          duration: 800
        });
      }
    });
  };

  return Cart;

})();

$(function() {
  var init;
  return init = new Init();
});
