<?php

namespace Bdloc\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository {

	public function getAllInformation() {
        /*$query = $this->getEntityManager()
            ->createQuery(
                'SELECT ticket, category FROM TicketsAppBundle:Ticket ticket
                JOIN ticket.category category'
            );*/

        /*SELECT * FROM book b
        LEFT JOIN serie s ON b.serie_id = s.id
        LEFT JOIN author a ON b.illustrator = a.id 
        LEFT JOIN author au ON b.scenarist = au.id 
        LEFT JOIN author aut ON b.colorist = aut.id
        WHERE b.id = 7*/

        $query = $this->createQueryBuilder('book')
            ->join('book.serie_id', 'category')
            ->join('ticket.user', 'user')
            ->getQuery();

            return $query->getResult();
    }
}
