<?php

namespace Bdloc\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends EntityRepository
{
	public function getCartEnCours($user) {
		/*	select b.id, b.title from cart c 

			JOIN cartitem ci ON ci.cart_id = c.id
			JOIN book b ON b.id = ci.book_id 
			WHERE c.user_id = '3'*/

		$query = $this->createQueryBuilder('cart')
		->addselect('book')
		->addselect('cartitem')
		->leftjoin('cart.cartItem', 'cartitem')
		->leftjoin('cartitem.book', 'book')
		->select('book.id, book.title')
		->where('cart.user = :id')
		->setParameter(':id', $user->getId())
		->getQuery();

        return $query->getResult();
	}
}
